import {
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  benefitIcon4,
  benefitImage2,
  chromecast,
  disc02,
  discord,
  discordBlack,
  facebook,
  figma,
  file02,
  neonService,
  // sliderlogo,
  framer,
  homeSmile,
  instagram,
  service,
  notification2,
  notification3,
  Frosty,
  Crunchy,
  Azas,
  BoutiquePapillon,
  CeramDecor,
  Cuanassa,
  Cuisima,
  DinaPerez,
  Elva,
  Fouad,
  LerableDor,
  LuckyTravel,
  MaraaiAwrass,
  Oppo,
  NewtechCeram,
  Plaza,
  Pokébowl,
  Securipcro,
  SoniaAttalah,
  WonderFood,
  Frenchy,
  Benpack,
  notification4,
  notion,
  photoshop,
  plusSquare,
  protopie,
  raindrop,
  recording01,
  recording03,
  benefitCard1,
  roadmap1,
  roadmap2,
  roadmap3,
  roadmap4,
  searchMd,
  slack,
  sliders04,
  telegram,
  twitter,
  // yourlogo,
  background,
  loup,
  card,
  cat,
  donut,
  joker,
  weed,
  batman,
  spiderman,
  superman,
  thanos,
  mario,
  manette,
  gum,
  america,
  thanos2,
  weedD,
  catD,
  smoke,
  donutD,
  manetteD,
  batmanD,
  spidermanD,
  supermanD,
  gumD,
  americaD,
  jokerD,
  thanosDD,
  smokeD,
  marioD,
  thanosD,
  carte1,
  carte2,
  carte3,
  carte4,
  carte5,
  carte6,
  carte7,
  carte8,
  carte9,
  carte10,
  carte11,
  carte12,
  carte13,
  carte14,
  carte15,
  carte1D,
  carte2D,
  carte3D,
  carte4D,
  carte5D,
  carte6D,
  carte7D,
  carte8D,
  carte9D,
  carte10D,
  carte11D,
  carte12D,
  carte13D,
  carte14D,
  carte15D,
} from '../assets'

export const products = [
  {
    id: 1,
    name: 'Heroes Poster',
    href: '#',
    imageSrc: thanos,
    imageAlt: "Front of men's Basic Tee in black.",
    price: '3500',
    heroes: [
      { imageSrc: catD, image: cat, name: 'cat' },
      { imageSrc: donutD, image: donut, name: 'donut' },
      { imageSrc: manetteD, image: manette, name: 'manette' },
      { imageSrc: batmanD, image: batman, name: 'batman' },
      { imageSrc: spidermanD, image: spiderman, name: 'spiderman' },
      { imageSrc: supermanD, image: superman, name: 'superman' },
      { imageSrc: gumD, image: gum, name: 'gum' },
      { imageSrc: americaD, image: america, name: 'america' },
      { imageSrc: jokerD, image: joker, name: 'joker ' },
      { imageSrc: thanosDD, image: thanos2, name: 'thanos' },
      { imageSrc: smokeD, image: smoke, name: 'smoke ' },
      { imageSrc: marioD, image: mario, name: ' mario' },
      { imageSrc: weedD, image: weed, name: ' weed ' },
      { imageSrc: thanosD, image: thanos, name: 'thanos2' },
    ],
    dimension: '60x40',
    stock: false,
    new: true,
    sizes: [{ name: '60x40' }],
  },

  {
    id: 2,
    name: 'Loup Garou',
    href: '#',
    imageSrc: loup,
    imageAlt: "Front of men's Classic Tee in black.",
    price: '3000',
    heroes: [{ imageSrc: loup, image: loup }],
    dimension: '60x40',
    stock: true,
    new: true,
    sizes: [{ name: '60x40', inStock: true }],
  },
  {
    id: 3,
    name: 'Cards',
    href: '#',
    heroes: [
      { imageSrc: carte1D, image: carte1 },
      { imageSrc: carte2D, image: carte2 },
      { imageSrc: carte3D, image: carte3 },
      { imageSrc: carte4D, image: carte4 },
      { imageSrc: carte5D, image: carte5 },
      { imageSrc: carte6D, image: carte6 },
      { imageSrc: carte7D, image: carte7 },
      { imageSrc: carte8D, image: carte8 },
      { imageSrc: carte9D, image: carte9 },
      { imageSrc: carte10D, image: carte10 },
      { imageSrc: carte11D, image: carte11 },
      { imageSrc: carte12D, image: carte12 },
      { imageSrc: carte13D, image: carte13 },
      { imageSrc: carte14D, image: carte14 },
      { imageSrc: carte15D, image: carte15 },
    ],
    imageSrc: card,
    imageAlt: "Front of men's Classic Tee in black.",
    price: '3000',
    dimension: '60x40',
    stock: false,
    new: true,
    sizes: [{ name: '60x40', inStock: true }],
  },
  {
    id: 4,
    name: 'Cards',
    href: '#',
    heroes: [
      { imageSrc: carte1D, image: carte1 },
      { imageSrc: carte2D, image: carte2 },
      { imageSrc: carte3D, image: carte3 },
      { imageSrc: carte4D, image: carte4 },
      { imageSrc: carte5D, image: carte5 },
      { imageSrc: carte6D, image: carte6 },
      { imageSrc: carte7D, image: carte7 },
      { imageSrc: carte8D, image: carte8 },
      { imageSrc: carte9D, image: carte9 },
      { imageSrc: carte10D, image: carte10 },
      { imageSrc: carte11D, image: carte11 },
      { imageSrc: carte12D, image: carte12 },
      { imageSrc: carte13D, image: carte13 },
      { imageSrc: carte14D, image: carte14 },
      { imageSrc: carte15D, image: carte15 },
    ],
    imageSrc: card,
    imageAlt: 'Wanted Cards',
    price: '3500',
    dimension: '60x40',
    stock: true,
    new: false,
    sizes: [{ name: '60x40', inStock: true }],
  },
]

export const navigation = [
  {
    id: '0',
    title: 'Home',
    url: '/',
  },
  {
    id: '1',
    title: 'Portfolio',
    url: '/portfolio',
  },

  {
    id: '2',
    title: 'Shop',
    url: '/Shop',
  },

  // {
  //   id: '3',
  //   title: 'Pricing',
  //   url: '/pricing',
  // },
  // {
  //   id: '4',
  //   title: 'New account',
  //   url: '#signup',
  //   onlyMobile: true,
  // },
  // {
  //   id: '5',
  //   title: 'Sign in',
  //   url: '#login',
  //   onlyMobile: true,
  // },
]

export const heroIcons = [homeSmile, file02, searchMd, plusSquare]

export const notificationImages = [notification4, notification3, notification2]

export const companyLogos = [
  Frosty,
  Crunchy,
  Azas,
  BoutiquePapillon,
  CeramDecor,
  Cuanassa,
  Cuisima,
  DinaPerez,
  Elva,
  Fouad,
  LerableDor,
  LuckyTravel,
  MaraaiAwrass,
  Oppo,
  NewtechCeram,
  Plaza,
  Pokébowl,
  Securipcro,
  SoniaAttalah,
  WonderFood,
  Frenchy,
  Benpack,
  // sliderlogo,
]

export const brainwaveServices = [
  'Shooting Profesionnel',
  'Shooting Artistique',
  'Shooting Produit',
]

export const brainwaveServicesIcons = [
  recording03,
  recording01,
  disc02,
  chromecast,
  sliders04,
]

export const roadmap = [
  {
    id: '0',
    title: 'Voice recognition',
    text: 'Enable the chatbot to understand and respond to voice commands, making it easier for users to interact with the app hands-free.',
    date: 'May 2023',
    status: 'done',
    imageUrl: roadmap1,
    colorful: true,
  },
  {
    id: '1',
    title: 'Gamification',
    text: 'Add game-like elements, such as badges or leaderboards, to incentivize users to engage with the chatbot more frequently.',
    date: 'May 2023',
    status: 'progress',
    imageUrl: roadmap2,
  },
  {
    id: '2',
    title: 'Chatbot customization',
    text: "Allow users to customize the chatbot's appearance and behavior, making it more engaging and fun to interact with.",
    date: 'May 2023',
    status: 'done',
    imageUrl: roadmap3,
  },
  {
    id: '3',
    title: 'Integration with APIs',
    text: 'Allow the chatbot to access external data sources, such as weather APIs or news APIs, to provide more relevant recommendations.',
    date: 'May 2023',
    status: 'progress',
    imageUrl: roadmap4,
  },
]

export const collabText =
  "With smart automation and top-notch security, it's the perfect solution for teams looking to work smarter."

export const collabContent = [
  {
    id: '0',
    title: 'Photo',
  },
  {
    id: '1',
    title: 'Video',
  },
  {
    id: '2',
    title: 'Weeding',
  },
  {
    id: '3',
    title: 'Graphic Design',
  },
  {
    id: '4',
    title: 'Visual Identity',
  },
  {
    id: '5',
    title: 'Printing',
  },
  {
    id: '6',
    title: 'Developement',
  },
  {
    id: '7',
    title: 'Packaging',
  },
]

export const collabApps = [
  {
    id: '0',
    title: 'Figma',
    icon: figma,
    width: 26,
    height: 36,
  },
  {
    id: '1',
    title: 'Notion',
    icon: notion,
    width: 34,
    height: 36,
  },
  {
    id: '2',
    title: 'Discord',
    icon: discord,
    width: 36,
    height: 28,
  },
  {
    id: '3',
    title: 'Slack',
    icon: slack,
    width: 34,
    height: 35,
  },
  {
    id: '4',
    title: 'Photoshop',
    icon: photoshop,
    width: 34,
    height: 34,
  },
  {
    id: '5',
    title: 'Protopie',
    icon: protopie,
    width: 34,
    height: 34,
  },
  {
    id: '6',
    title: 'Framer',
    icon: framer,
    width: 26,
    height: 34,
  },
  {
    id: '7',
    title: 'Raindrop',
    icon: raindrop,
    width: 38,
    height: 32,
  },
]

export const pricing = [
  {
    id: '0',
    title: 'E-commerce ',
    description: 'AI chatbot, personalized recommendations',
    price: '0',
    features: [
      'An AI chatbot that can understand your queries',
      'Personalized recommendations based on your preferences',
      'Ability to explore the app and its features without any cost',
      'dqsdsqdqs',
    ],
  },
  {
    id: '1',
    title: 'Brand Identity',
    description: 'Advanced AI chatbot, priority support, analytics dashboard',
    price: '15000',
    features: [
      'An advanced AI chatbot that can understand complex queries',
      'An analytics dashboard to track your conversations',
      'Priority support to solve issues quickly',
    ],
  },
  {
    id: '2',
    title: 'Start-up',
    description: 'Custom AI chatbot, advanced analytics, dedicated account',
    price: null,
    features: [
      'An AI chatbot that can understand your queries',
      'Personalized recommendations based on your preferences',
      'Ability to explore the app and its features without any cost',
    ],
  },
  {
    id: '3',
    title: 'Start-up',
    description: 'Custom AI chatbot, advanced analytics, dedicated account',
    price: null,
    features: [
      'An AI chatbot that can understand your queries',
      'Personalized recommendations based on your preferences',
      'Ability to explore the app and its features without any cost',
    ],
  },
]

export const benefits = [
  {
    id: '0',
    title: 'Photo / Video',
    text: 'Lets users quickly find answers to their questions without having to search through multiple sources.',
    backgroundUrl: './src/assets/benefits/card-1.svg',
    iconUrl: benefitIcon1,
    imageUrl: service,
    url: '/photo',
  },
  {
    id: '1',
    title: 'Infographie',
    text: 'The app uses natural language processing to understand user queries and provide accurate and relevant responses.',
    backgroundUrl: './src/assets/benefits/card-2.svg',
    iconUrl: benefitIcon2,
    imageUrl: service,
    url: '/infographie',
  },
  {
    id: '2',
    title: 'Weeding',
    text: 'Connect with the AI chatbot from anywhere, on any device, making it more accessible and convenient.',
    backgroundUrl: './src/assets/benefits/card-3.svg',
    iconUrl: benefitIcon3,
    imageUrl: service,
    light: true,
    url: '/weeding',
  },
  {
    id: '3',
    title: 'Development',
    text: 'Lets users quickly find answers to their questions without having to search through multiple sources.',
    backgroundUrl: './src/assets/benefits/card-4.svg',
    iconUrl: benefitIcon4,
    imageUrl: service,
    light: true,
    url: '/dev',
  },
  {
    id: '4',
    title: 'Audio',
    text: 'Lets users quickly find answers to their questions without having to search through multiple sources.',
    backgroundUrl: './src/assets/benefits/card-5.svg',
    iconUrl: benefitIcon1,
    imageUrl: service,
    url: '/audio',
  },
  {
    id: '5',
    title: 'Neon',
    text: 'The app uses natural language processing to understand user queries and provide accurate and relevant responses.',
    backgroundUrl: './src/assets/benefits/card-6.svg',
    iconUrl: benefitIcon2,
    imageUrl: neonService,
    url: '/neon',
  },
]

export const socials = [
  // {
  //   id: '0',
  //   title: 'Discord',
  //   iconUrl: discordBlack,
  //   url: '#',
  // },
  {
    id: '1',
    title: 'Twitter',
    iconUrl: twitter,
    url: 'https://www.tiktok.com/@pixel.creativeagency',
  },
  {
    id: '2',
    title: 'Instagram',
    iconUrl: instagram,
    url: 'https://www.instagram.com/pixel.photolab',
  },
  {
    id: '3',
    title: 'Telegram',
    iconUrl: telegram,
    url: 'https://www.tiktok.com/@pixel.creativeagency',
  },
  {
    id: '4',
    title: 'Facebook',
    iconUrl: facebook,
    url: 'https://www.facebook.com/pixel.lab.3110?mibextid=LQQJ4d',
  },
]
